apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azdo-agents
  labels:
    app: azdevops-agent
spec:
  replicas: 2 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: devopsagent
        image: chhouse/arm64azdodockeragent:v7
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
        livenessProbe:
          exec:
            command:
            - /azp/agent-health.sh
          initialDelaySeconds: 180
          periodSeconds: 5
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
